spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    s3:
      url: ${AWS_S3_URL}
      bucket: ${AWS_S3_BUCKET_NAME}
      path:
        parking-space-image: ${PARKING_SPACE_IMAGE}
        map-image: ${MAP_IMAGE}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
